### ISSUE TITLE
How to install without npm?

### ISSUE THREAD

**Issue by timmfin** [TrevorBurnham/Jitter#1]
NPM is down right now (http://github.com/isaacs/npm/issues#issue/266 and http://groups.google.com/group/npm-/browse_thread/thread/5573b40cbb55de3c). Is there any way to install Jitter without npm?

**Comment by TrevorBurnham** [comment]
Hmm, try doing this:
1. Copy the contents of the `bin` directory into the Node.js bin directory (on my machine, using Homebrew, it's `/usr/local/Cellar/node/0.2.0/bin`) and ensure that directory is on your PATH.
2. Copy the `lib` directory as `jitter-0.9.2` into the Node.js lib directory (for me, it's `/Users/trevor/.node_libraries/`).

A bit complicated, I'm afraid. That's why I decided to make npm the only official way of installing Jitter; there's no easier way of adding JS libraries to Node.

**Comment by TrevorBurnham** [comment]
Sorry, here's the better, simpler answer to this question: As long as you already have `npm` installed, you can download the Jitter source and run

```
npm install .
```

from the source directory, rather than doing a remote install. I've added this to the README. Thanks for raising the issue.
