### ISSUE TITLE
Use fs.watch() instead of fs.watchFile()

### ISSUE THREAD

**Issue by nfarina** [TrevorBurnham/Jitter#23]
I often use `fs_usage` to monitor what apps are misbehaving on my system when my battery life seems to be running down faster than usual. And I've noticed that jitter will cause a lot of repeated filesystem activity when it's running, which for me is always.

I believe this is because jitter uses `fs.watchFile()`, which is polling-based on the Mac.

Can jitter be made to use `fs.watch()` instead? This is what `coffee --watch` uses and is the only reason I can't use jitter!

**Comment by nfarina** [comment]
OK, now that I've tried to add support for this myself, I am starting to understand why `fs.watch` isn't used. It doesn't even generate change notifications on my machine (OS X 10.8.2).

I'd still be curious to know if it's possible! Closing this issue in the meantime.

**Comment by TrevorBurnham** [comment]
Yeah, `fs.watch` is better than `fs.watchFile` in some ways (mainly, Windows support and less system resource usage), but also has some unfortunate inconsistencies. Continuing to use `fs.watchFile` in Jitter was an intentional decision: Since `coffee -cw` uses `fs.watch`, this gives CoffeeScript devs a choice between two imperfect options.

CoffeeScript uses some hacks to make `fs.watch` work reasonably well; see http://coffeescript.org/documentation/docs/command.html. Also see much discussion at the CoffeeScript issue tracker, e.g. https://github.com/jashkenas/coffee-script/pull/1846.

**Comment by nfarina** [comment]
Oy vey, what a cluster. Looks like the only thing to do is wait for Node to deliver on fs.watch() which is looking like a very long-term project.

Ah well, we switched back to Jitter for its many other benefits, guess I can live with some file-polling for a while yet!
